import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import Link from 'next/link';

export default function Home({ posts }) {
    return (
        <div>
            <Head>
                <title>Cassady Campos Software</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="mt-4">
                <div className="flex flex-wrap row text-left">
                    <h1 className={styles.title}>
                        Hi, I'm Cassady Campos
                    </h1>
                    <div className={styles.title}>Software Developer</div>

                    <div className={styles.description + " col-md-10"}>
                        In love with all things tech and software.
                        Have a look around, check out one of my projects or read an article from my blog, or just play around!
                    </div>
                    <Link href="#projects">Lets get going!</Link>
                </div>

                <div className="mt-5" id="projects">
                    <h3>Have a look at some of my posts</h3>
                    <div className={styles.grid}>
                        <div className="">
                            {posts.map((post, index) => (
                                <Link
                                    href={'/blog/' + post.slug}
                                    passHref
                                    key={index}
                                >
                                    <div
                                        className="card mb-3 pointer"
                                        style={{ maxWidth: '540px' }}
                                    >
                                        <div className="row g-0">
                                            <div className="col-md-8">
                                                <div className="card-body">
                                                    <h5 className="card-title">
                                                        {post.frontMatter.title}
                                                    </h5>
                                                    <p className="card-text">
                                                        {
                                                            post.frontMatter
                                                                .description
                                                        }
                                                    </p>
                                                    <p className="card-text">
                                                        <small className="text-muted">
                                                            {
                                                                post.frontMatter
                                                                    .date
                                                            }
                                                        </small>
                                                    </p>
                                                </div>
                                            </div>
                                            <div className="col-md-4 m-auto">
                                                <Image
                                                    src={
                                                        post.frontMatter
                                                            .thumbnailUrl
                                                    }
                                                    className="img-fluid mt-1 rounded-start"
                                                    alt="thumbnail"
                                                    width={500}
                                                    height={400}
                                                    objectFit="cover"
                                                />
                                            </div>
                                        </div>
                                    </div>
                                </Link>
                            ))}
                        </div>
                    </div>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
}

export const getStaticProps = async () => {
    const files = fs.readdirSync(path.join('posts'));
    const posts = files.map((filename) => {
        const markdownWithMeta = fs.readFileSync(
            path.join('posts', filename),
            'utf-8'
        );
        const { data: frontMatter } = matter(markdownWithMeta);
        return {
            frontMatter,
            slug: filename.split('.')[0],
        };
    });

    return {
        props: {
            posts,
        },
    };
};
